### ISSUE TITLE
Build fails with "Error: module bitarray is in file 'undeaD/src/undead/bitarray.d' which cannot be read"

### ISSUE THREAD

**Issue by hartzell** [biod/sambamba#312]
I'm working on a [Spack](https://spack.io) package for sambamba.

I'm currently trying to build 0.6.6.

The build is failing with this error message:

```
ldmd2 @sambamba-ldmd-release.rsp
Error: module bitarray is in file 'undeaD/src/undead/bitarray.d' which cannot be read
import path[0] = /home/hartzelg/tmp/spack-d/opt/spack/linux-centos7-x86_64/gcc-5.4.0/ldc-1.3.0-r4s54s2ks6z5b77y5s3tfi43tz2jvqu5/include/d/ldc
import path[1] = /home/hartzelg/tmp/spack-d/opt/spack/linux-centos7-x86_64/gcc-5.4.0/ldc-1.3.0-r4s54s2ks6z5b77y5s3tfi43tz2jvqu5/include/d
import path[2] = BioD/
import path[3] = undeaD/src/
import path[4] = .                                                                                                                                                                                   make: *** [sambamba-ldmd2-64] Error 1
==> Error: ProcessError: Command exited with status 2:
```

I notice that, unlike `BioD`, there is no submodule for `undeaD` and that it is [ignored in the .gitignore](https://github.com/lomereiter/sambamba/blob/master/.gitignore#L2).

I've seen the instructions about cloning `https://github.com/dlang/undeaD` but I have no way to know which commit/version/release/tag is known to work with a given Sambamba release.

My life would be easiest (not everyone's goal, I know :smile:) if there were a submodule for `undeadD` like you have for `BioD`.

Failing that, is there a [particular release](https://github.com/dlang/undeaD/releases) of `undeaD` that you recommend for `sambamba@0.6.6`?

Thanks!

**Comment by lomereiter** [comment]
Hi, thanks for letting me know of yet another package manager!
You can use any of 1.0.5–1.0.7 versions (I don't think they change any code, it only gets added, since `undead` repo functions as a kind of purgatory for whatever parts of the standard library that fail to meet its ever higher standards)

I've been also arguing for a submodule but @pjotrp is very firmly convinced that they are evil 👿 
Citation from one of his e-mails (I suppose he doesn't mind):
> Based on long experience in other projects: submodules tend to mess
up, it is a complexity that tries to solves dependencies, something
best left to the deployment system. I have no use for git modules and
I think BioD and htslib should be a libraries and undeaD should be
removed.

**Comment by hartzell** [comment]
I've been trained to avoid them too, but I figured since there was already *one* there, what could another hurt....

**Comment by pjotrp** [comment]
In the instructions we should clone a specific version of unDead, I agree. Last time I tried latest worked, but that may change.

**Comment by pjotrp** [comment]
It is a git submodule now.
